"""Fixed F&O stock universe used by V1.

This list is intentionally static for V1. It contains the 210 stocks
provided for this project and represents the underlying stocks we monitor.
"""

FNO_STOCKS = [
    {"name": '360 ONE WAM LIMITED', "symbol": '360ONE'},
    {"name": 'ABB India Limited', "symbol": 'ABB'},
    {"name": 'APL Apollo Tubes Limited', "symbol": 'APLAPOLLO'},
    {"name": 'AU Small Finance Bank Limited', "symbol": 'AUBANK'},
    {"name": 'Adani Energy Solutions Limited', "symbol": 'ADANIENSOL'},
    {"name": 'Adani Enterprises Limited', "symbol": 'ADANIENT'},
    {"name": 'Adani Green Energy Limited', "symbol": 'ADANIGREEN'},
    {"name": 'Adani Ports and Special Economic Zone Limited', "symbol": 'ADANIPORTS'},
    {"name": 'Adani Power Limited', "symbol": 'ADANIPOWER'},
    {"name": 'Aditya Birla Capital Limited', "symbol": 'ABCAPITAL'},
    {"name": 'Alkem Laboratories Limited', "symbol": 'ALKEM'},
    {"name": 'Amber Enterprises India Limited', "symbol": 'AMBER'},
    {"name": 'Ambuja Cements Limited', "symbol": 'AMBUJACEM'},
    {"name": 'Angel One Limited', "symbol": 'ANGELONE'},
    {"name": 'Apollo Hospitals Enterprise Limited', "symbol": 'APOLLOHOSP'},
    {"name": 'Ashok Leyland Limited', "symbol": 'ASHOKLEY'},
    {"name": 'Asian Paints Limited', "symbol": 'ASIANPAINT'},
    {"name": 'Astral Limited', "symbol": 'ASTRAL'},
    {"name": 'Ather Energy Limited', "symbol": 'ATHERENERG'},
    {"name": 'Aurobindo Pharma Limited', "symbol": 'AUROPHARMA'},
    {"name": 'Avenue Supermarts Limited', "symbol": 'DMART'},
    {"name": 'Axis Bank Limited', "symbol": 'AXISBANK'},
    {"name": 'BSE Limited', "symbol": 'BSE'},
    {"name": 'Bajaj Auto Limited', "symbol": 'BAJAJ-AUTO'},
    {"name": 'Bajaj Finance Limited', "symbol": 'BAJFINANCE'},
    {"name": 'Bajaj Finserv Limited', "symbol": 'BAJAJFINSV'},
    {"name": 'Bajaj Holdings & Investment Limited', "symbol": 'BAJAJHLDNG'},
    {"name": 'Bandhan Bank Limited', "symbol": 'BANDHANBNK'},
    {"name": 'Bank of Baroda', "symbol": 'BANKBARODA'},
    {"name": 'Bank of India', "symbol": 'BANKINDIA'},
    {"name": 'Bank of Maharashtra', "symbol": 'MAHABANK'},
    {"name": 'Bharat Dynamics Limited', "symbol": 'BDL'},
    {"name": 'Bharat Electronics Limited', "symbol": 'BEL'},
    {"name": 'Bharat Forge Limited', "symbol": 'BHARATFORG'},
    {"name": 'Bharat Heavy Electricals Limited', "symbol": 'BHEL'},
    {"name": 'Bharat Petroleum Corporation Limited', "symbol": 'BPCL'},
    {"name": 'Bharti Airtel Limited', "symbol": 'BHARTIARTL'},
    {"name": 'Biocon Limited', "symbol": 'BIOCON'},
    {"name": 'Blue Star Limited', "symbol": 'BLUESTARCO'},
    {"name": 'Bosch Limited', "symbol": 'BOSCHLTD'},
    {"name": 'Britannia Industries Limited', "symbol": 'BRITANNIA'},
    {"name": 'CG Power and Industrial Solutions Limited', "symbol": 'CGPOWER'},
    {"name": 'Canara Bank', "symbol": 'CANBK'},
    {"name": 'Central Depository Services (India) Limited', "symbol": 'CDSL'},
    {"name": 'Cholamandalam Investment and Finance Company Limited', "symbol": 'CHOLAFIN'},
    {"name": 'Cipla Limited', "symbol": 'CIPLA'},
    {"name": 'Coal India Limited', "symbol": 'COALINDIA'},
    {"name": 'Cochin Shipyard Limited', "symbol": 'COCHINSHIP'},
    {"name": 'Coforge Limited', "symbol": 'COFORGE'},
    {"name": 'Colgate Palmolive (India) Limited', "symbol": 'COLPAL'},
    {"name": 'Computer Age Management Services Limited', "symbol": 'CAMS'},
    {"name": 'Container Corporation of India Limited', "symbol": 'CONCOR'},
    {"name": 'Crompton Greaves Consumer Electricals Limited', "symbol": 'CROMPTON'},
    {"name": 'Cummins India Limited', "symbol": 'CUMMINSIND'},
    {"name": 'DLF Limited', "symbol": 'DLF'},
    {"name": 'Dabur India Limited', "symbol": 'DABUR'},
    {"name": 'Delhivery Limited', "symbol": 'DELHIVERY'},
    {"name": "Divi's Laboratories Limited", "symbol": 'DIVISLAB'},
    {"name": 'Dixon Technologies (India) Limited', "symbol": 'DIXON'},
    {"name": "Dr. Reddy's Laboratories Limited", "symbol": 'DRREDDY'},
    {"name": 'ETERNAL LIMITED', "symbol": 'ETERNAL'},
    {"name": 'Eicher Motors Limited', "symbol": 'EICHERMOT'},
    {"name": 'FORCE MOTORS LTD', "symbol": 'FORCEMOT'},
    {"name": 'FSN E-Commerce Ventures Limited', "symbol": 'NYKAA'},
    {"name": 'Fortis Healthcare Limited', "symbol": 'FORTIS'},
    {"name": 'GAIL (India) Limited', "symbol": 'GAIL'},
    {"name": 'GE Vernova T&D India Limited', "symbol": 'GVT&D'},
    {"name": 'GMR AIRPORTS LIMITED', "symbol": 'GMRAIRPORT'},
    {"name": 'Glenmark Pharmaceuticals Limited', "symbol": 'GLENMARK'},
    {"name": 'Godfrey Phillips India Limited', "symbol": 'GODFRYPHLP'},
    {"name": 'Godrej Consumer Products Limited', "symbol": 'GODREJCP'},
    {"name": 'Godrej Properties Limited', "symbol": 'GODREJPROP'},
    {"name": 'Grasim Industries Limited', "symbol": 'GRASIM'},
    {"name": 'HCL Technologies Limited', "symbol": 'HCLTECH'},
    {"name": 'HDFC Asset Management Company Limited', "symbol": 'HDFCAMC'},
    {"name": 'HDFC Bank Limited', "symbol": 'HDFCBANK'},
    {"name": 'HDFC Life Insurance Company Limited', "symbol": 'HDFCLIFE'},
    {"name": 'Havells India Limited', "symbol": 'HAVELLS'},
    {"name": 'Hero MotoCorp Limited', "symbol": 'HEROMOTOCO'},
    {"name": 'Hindalco Industries Limited', "symbol": 'HINDALCO'},
    {"name": 'Hindustan Aeronautics Limited', "symbol": 'HAL'},
    {"name": 'Hindustan Petroleum Corporation Limited', "symbol": 'HINDPETRO'},
    {"name": 'Hindustan Unilever Limited', "symbol": 'HINDUNILVR'},
    {"name": 'Hindustan Zinc Limited', "symbol": 'HINDZINC'},
    {"name": 'Hitachi Energy India Limited', "symbol": 'POWERINDIA'},
    {"name": 'Hyundai Motor India Limited', "symbol": 'HYUNDAI'},
    {"name": 'ICICI Bank Limited', "symbol": 'ICICIBANK'},
    {"name": 'ICICI Lombard General Insurance Company Limited', "symbol": 'ICICIGI'},
    {"name": 'ICICI Prudential Life Insurance Company Limited', "symbol": 'ICICIPRULI'},
    {"name": 'IDFC First Bank Limited', "symbol": 'IDFCFIRSTB'},
    {"name": 'ITC Limited', "symbol": 'ITC'},
    {"name": 'Indian Bank', "symbol": 'INDIANB'},
    {"name": 'Indian Energy Exchange Limited', "symbol": 'IEX'},
    {"name": 'Indian Oil Corporation Limited', "symbol": 'IOC'},
    {"name": 'Indian Railway Finance Corporation Limited', "symbol": 'IRFC'},
    {"name": 'Indian Renewable Energy Development Agency Limited', "symbol": 'IREDA'},
    {"name": 'Indus Towers Limited', "symbol": 'INDUSTOWER'},
    {"name": 'IndusInd Bank Limited', "symbol": 'INDUSINDBK'},
    {"name": 'Info Edge (India) Limited', "symbol": 'NAUKRI'},
    {"name": 'Infosys Limited', "symbol": 'INFY'},
    {"name": 'Inox Wind Limited', "symbol": 'INOXWIND'},
    {"name": 'InterGlobe Aviation Limited', "symbol": 'INDIGO'},
    {"name": 'JINDAL STEEL LIMITED', "symbol": 'JINDALSTEL'},
    {"name": 'JSW Energy Limited', "symbol": 'JSWENERGY'},
    {"name": 'JSW Steel Limited', "symbol": 'JSWSTEEL'},
    {"name": 'Jio Financial Services Limited', "symbol": 'JIOFIN'},
    {"name": 'Jubilant Foodworks Limited', "symbol": 'JUBLFOOD'},
    {"name": 'KEI Industries Limited', "symbol": 'KEI'},
    {"name": 'KPIT Technologies Limited', "symbol": 'KPITTECH'},
    {"name": 'Kalyan Jewellers India Limited', "symbol": 'KALYANKJIL'},
    {"name": 'Kaynes Technology India Limited', "symbol": 'KAYNES'},
    {"name": 'Kfin Technologies Limited', "symbol": 'KFINTECH'},
    {"name": 'Kotak Mahindra Bank Limited', "symbol": 'KOTAKBANK'},
    {"name": 'L&T Finance Limited', "symbol": 'LTF'},
    {"name": 'LIC Housing Finance Limited', "symbol": 'LICHSGFIN'},
    {"name": 'LTM Limited', "symbol": 'LTM'},
    {"name": 'Larsen & Toubro Limited', "symbol": 'LT'},
    {"name": 'Laurus Labs Limited', "symbol": 'LAURUSLABS'},
    {"name": 'Life Insurance Corporation Of India', "symbol": 'LICI'},
    {"name": 'Lodha Developers Limited', "symbol": 'LODHA'},
    {"name": 'Lupin Limited', "symbol": 'LUPIN'},
    {"name": 'Mahindra & Mahindra Limited', "symbol": 'M&M'},
    {"name": 'Manappuram Finance Limited', "symbol": 'MANAPPURAM'},
    {"name": 'Mankind Pharma Limited', "symbol": 'MANKIND'},
    {"name": 'Marico Limited', "symbol": 'MARICO'},
    {"name": 'Maruti Suzuki India Limited', "symbol": 'MARUTI'},
    {"name": 'Max Financial Services Limited', "symbol": 'MFSL'},
    {"name": 'Max Healthcare Institute Limited', "symbol": 'MAXHEALTH'},
    {"name": 'Mazagon Dock Shipbuilders Limited', "symbol": 'MAZDOCK'},
    {"name": 'Motilal Oswal Financial Services Limited', "symbol": 'MOTILALOFS'},
    {"name": 'MphasiS Limited', "symbol": 'MPHASIS'},
    {"name": 'Multi Commodity Exchange of India Limited', "symbol": 'MCX'},
    {"name": 'Muthoot Finance Limited', "symbol": 'MUTHOOTFIN'},
    {"name": 'NBCC (India) Limited', "symbol": 'NBCC'},
    {"name": 'NHPC Limited', "symbol": 'NHPC'},
    {"name": 'NMDC Limited', "symbol": 'NMDC'},
    {"name": 'NTPC Limited', "symbol": 'NTPC'},
    {"name": 'National Aluminium Company Limited', "symbol": 'NATIONALUM'},
    {"name": 'Nestle India Limited', "symbol": 'NESTLEIND'},
    {"name": 'Nippon Life India Asset Management Limited', "symbol": 'NAM-INDIA'},
    {"name": 'Oberoi Realty Limited', "symbol": 'OBEROIRLTY'},
    {"name": 'Oil & Natural Gas Corporation Limited', "symbol": 'ONGC'},
    {"name": 'Oil India Limited', "symbol": 'OIL'},
    {"name": 'One 97 Communications Limited', "symbol": 'PAYTM'},
    {"name": 'Oracle Financial Services Software Limited', "symbol": 'OFSS'},
    {"name": 'PB Fintech Limited', "symbol": 'POLICYBZR'},
    {"name": 'PG Electroplast Limited', "symbol": 'PGEL'},
    {"name": 'PI Industries Limited', "symbol": 'PIIND'},
    {"name": 'PNB Housing Finance Limited', "symbol": 'PNBHOUSING'},
    {"name": 'Page Industries Limited', "symbol": 'PAGEIND'},
    {"name": 'Patanjali Foods Limited', "symbol": 'PATANJALI'},
    {"name": 'Persistent Systems Limited', "symbol": 'PERSISTENT'},
    {"name": 'Petronet LNG Limited', "symbol": 'PETRONET'},
    {"name": 'Pidilite Industries Limited', "symbol": 'PIDILITIND'},
    {"name": 'Polycab India Limited', "symbol": 'POLYCAB'},
    {"name": 'Power Finance Corporation Limited', "symbol": 'PFC'},
    {"name": 'Power Grid Corporation of India Limited', "symbol": 'POWERGRID'},
    {"name": 'Premier Energies Limited', "symbol": 'PREMIERENE'},
    {"name": 'Prestige Estates Projects Limited', "symbol": 'PRESTIGE'},
    {"name": 'Punjab National Bank', "symbol": 'PNB'},
    {"name": 'RBL Bank Limited', "symbol": 'RBLBANK'},
    {"name": 'REC Limited', "symbol": 'RECLTD'},
    {"name": 'Radico Khaitan Limited', "symbol": 'RADICO'},
    {"name": 'Rail Vikas Nigam Limited', "symbol": 'RVNL'},
    {"name": 'Reliance Industries Limited', "symbol": 'RELIANCE'},
    {"name": 'SAGILITY LIMITED', "symbol": 'SAGILITY'},
    {"name": 'SBI Cards and Payment Services Limited', "symbol": 'SBICARD'},
    {"name": 'SBI Life Insurance Company Limited', "symbol": 'SBILIFE'},
    {"name": 'SHREE CEMENT LIMITED', "symbol": 'SHREECEM'},
    {"name": 'SRF Limited', "symbol": 'SRF'},
    {"name": 'Samvardhana Motherson International Limited', "symbol": 'MOTHERSON'},
    {"name": 'Shriram Finance Limited', "symbol": 'SHRIRAMFIN'},
    {"name": 'Siemens Limited', "symbol": 'SIEMENS'},
    {"name": 'Solar Industries India Limited', "symbol": 'SOLARINDS'},
    {"name": 'Sona BLW Precision Forgings Limited', "symbol": 'SONACOMS'},
    {"name": 'State Bank of India', "symbol": 'SBIN'},
    {"name": 'Steel Authority of India Limited', "symbol": 'SAIL'},
    {"name": 'Sun Pharmaceutical Industries Limited', "symbol": 'SUNPHARMA'},
    {"name": 'Supreme Industries Limited', "symbol": 'SUPREMEIND'},
    {"name": 'Suzlon Energy Limited', "symbol": 'SUZLON'},
    {"name": 'Swiggy Limited', "symbol": 'SWIGGY'},
    {"name": 'TATA CONSUMER PRODUCTS LIMITED', "symbol": 'TATACONSUM'},
    {"name": 'TVS Motor Company Limited', "symbol": 'TVSMOTOR'},
    {"name": 'Tata Consultancy Services Limited', "symbol": 'TCS'},
    {"name": 'Tata Elxsi Limited', "symbol": 'TATAELXSI'},
    {"name": 'Tata Motors Passenger Vehicles Limited', "symbol": 'TMPV'},
    {"name": 'Tata Power Company Limited', "symbol": 'TATAPOWER'},
    {"name": 'Tata Steel Limited', "symbol": 'TATASTEEL'},
    {"name": 'Tech Mahindra Limited', "symbol": 'TECHM'},
    {"name": 'The Federal Bank Limited', "symbol": 'FEDERALBNK'},
    {"name": 'The Indian Hotels Company Limited', "symbol": 'INDHOTEL'},
    {"name": 'The Phoenix Mills Limited', "symbol": 'PHOENIXLTD'},
    {"name": 'Titan Company Limited', "symbol": 'TITAN'},
    {"name": 'Torrent Pharmaceuticals Limited', "symbol": 'TORNTPHARM'},
    {"name": 'Trent Limited', "symbol": 'TRENT'},
    {"name": 'Tube Investments of India Limited', "symbol": 'TIINDIA'},
    {"name": 'UNO Minda Limited', "symbol": 'UNOMINDA'},
    {"name": 'UPL Limited', "symbol": 'UPL'},
    {"name": 'UltraTech Cement Limited', "symbol": 'ULTRACEMCO'},
    {"name": 'Union Bank of India', "symbol": 'UNIONBANK'},
    {"name": 'United Spirits Limited', "symbol": 'UNITDSPR'},
    {"name": 'Varun Beverages Limited', "symbol": 'VBL'},
    {"name": 'Vedanta Limited', "symbol": 'VEDL'},
    {"name": 'Vishal Mega Mart Limited', "symbol": 'VMM'},
    {"name": 'Vodafone Idea Limited', "symbol": 'IDEA'},
    {"name": 'Voltas Limited', "symbol": 'VOLTAS'},
    {"name": 'Waaree Energies Limited', "symbol": 'WAAREEENER'},
    {"name": 'Wipro Limited', "symbol": 'WIPRO'},
    {"name": 'Yes Bank Limited', "symbol": 'YESBANK'},
    {"name": 'Zydus Lifesciences Limited', "symbol": 'ZYDUSLIFE'},
]


def get_symbols() -> list[str]:
    """Return the NSE symbols used by the monitoring/data-provider layer."""
    return [stock["symbol"] for stock in FNO_STOCKS]


def validate_stocks() -> list[str]:
    """Validate the fixed stock universe and return validation errors."""
    errors: list[str] = []

    if len(FNO_STOCKS) != 210:
        errors.append(f"Expected 210 stocks, found {len(FNO_STOCKS)}.")

    symbols = get_symbols()

    if len(symbols) != len(set(symbols)):
        duplicates = sorted({s for s in symbols if symbols.count(s) > 1})
        errors.append(f"Duplicate symbols found: {duplicates}")

    for index, stock in enumerate(FNO_STOCKS, start=1):
        if not stock.get("name", "").strip():
            errors.append(f"Stock #{index} has an empty name.")
        if not stock.get("symbol", "").strip():
            errors.append(f"Stock #{index} has an empty symbol.")

    return errors
